FROM ros:kinetic-perception

ARG VINS_BUILD_JOBS=1
ENV CERES_VERSION="1.12.0"
ENV CATKIN_WS=/root/catkin_ws

RUN apt-get update && apt-get install -y \
      cmake \
      git \
      libatlas-base-dev \
      libeigen3-dev \
      libgoogle-glog-dev \
      libsuitesparse-dev \
      python-catkin-tools \
      ros-${ROS_DISTRO}-cv-bridge \
      ros-${ROS_DISTRO}-image-transport \
      ros-${ROS_DISTRO}-message-filters \
      ros-${ROS_DISTRO}-tf && \
    rm -rf /var/lib/apt/lists/* && \
    git clone https://ceres-solver.googlesource.com/ceres-solver && \
    cd ceres-solver && \
    git checkout tags/${CERES_VERSION} && \
    mkdir build && cd build && \
    cmake .. && \
    make -j${VINS_BUILD_JOBS} install && \
    rm -rf ../../ceres-solver && \
    mkdir -p ${CATKIN_WS}/src/VINS-Fusion/

COPY ./ ${CATKIN_WS}/src/VINS-Fusion/

WORKDIR ${CATKIN_WS}
ENV TERM=xterm
ENV PYTHONIOENCODING=UTF-8
RUN catkin config \
      --extend /opt/ros/${ROS_DISTRO} \
      --cmake-args \
        -DCMAKE_BUILD_TYPE=Release && \
    catkin build -j${VINS_BUILD_JOBS} -p${VINS_BUILD_JOBS} && \
    sed -i '/exec "$@"/i \
            source "/root/catkin_ws/devel/setup.bash"' /ros_entrypoint.sh
